"""empty message

Revision ID: 307cb23e862b
Revises: a49b2af4a92c
Create Date: 2019-04-03 12:06:22.690524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307cb23e862b'
down_revision = 'a49b2af4a92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negatives_debates',
    sa.Column('negative_id', sa.Integer(), nullable=True),
    sa.Column('debate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['debate_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['negative_id'], ['user.id'], )
    )
    op.create_table('affirmatives_debates',
    sa.Column('affirmative_id', sa.Integer(), nullable=True),
    sa.Column('debate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['affirmative_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['debate_id'], ['debate.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affirmatives_debates')
    op.drop_table('negatives_debates')
    # ### end Alembic commands ###
