"""empty message

Revision ID: 566984218eb0
Revises: d2f773c3c3a2
Create Date: 2019-04-03 12:24:57.529921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566984218eb0'
down_revision = 'd2f773c3c3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debate', sa.Column('topic', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debate', 'topic')
    # ### end Alembic commands ###
