"""empty message

Revision ID: a49b2af4a92c
Revises: 
Create Date: 2019-04-02 17:15:46.861833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49b2af4a92c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('debate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affirmative_id', sa.Integer(), nullable=True),
    sa.Column('negative_id', sa.Integer(), nullable=True),
    sa.Column('affirmative_constructive', sa.Text(), nullable=True),
    sa.Column('negative_constructive', sa.Text(), nullable=True),
    sa.Column('affirmative_rebuttal', sa.Text(), nullable=True),
    sa.Column('negative_rebuttal', sa.Text(), nullable=True),
    sa.Column('affirmative_rejoinder', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['affirmative_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['negative_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debate')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
