"""empty message

Revision ID: d2f773c3c3a2
Revises: 307cb23e862b
Create Date: 2019-04-03 12:19:23.780267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f773c3c3a2'
down_revision = '307cb23e862b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('negatives_debates')
    op.drop_table('affirmatives_debates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affirmatives_debates',
    sa.Column('affirmative_id', sa.INTEGER(), nullable=True),
    sa.Column('debate_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['affirmative_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['debate_id'], ['debate.id'], )
    )
    op.create_table('negatives_debates',
    sa.Column('negative_id', sa.INTEGER(), nullable=True),
    sa.Column('debate_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['debate_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['negative_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
