"""empty message

Revision ID: f1ae2daf357a
Revises: 566984218eb0
Create Date: 2019-04-16 12:48:01.068712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ae2daf357a'
down_revision = '566984218eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debate', sa.Column('affirmative_title', sa.Text(), nullable=True))
    op.add_column('debate', sa.Column('negative_title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debate', 'negative_title')
    op.drop_column('debate', 'affirmative_title')
    # ### end Alembic commands ###
